- hosts: ubuntu
  become: yes
  tasks:

    - name: install openjdk-8-jdk
      apt:
        name: openjdk-8-jdk
        state: latest

    - name: install mave
      apt:
        name: maven
        state: latest
   
    - name: install git
      apt:
        name: git
        state: latest

    - name: git clone
      git:
        repo: https://github.com/wkhanvisualpathit/VProfile.git
        dest: /home/ansadm/project

    - name: get artifact
      shell: mvn -f /home/ansadm/project package

    - name: download tomcat
      get_url:
        url: http://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.45/bin/apache-tomcat-8.5.45.tar.gz
        dest: /home/ansadm
        remote_src: yes

    - name: unzip tar file
      unarchive:
         src: /home/ansadm/apache-tomcat-8.5.45.tar.gz 
         dest: /home/ansadm
         remote_src: yes

    - name: copy war file
      copy:
        src: /home/ansadm/project/target/vprofile-v1.war 
        dest: /home/ansadm/apache-tomcat-8.5.45/webapps
        remote_src: yes

    - name: start tomcat
      shell: nohup /home/ansadm/apache-tomcat-8.5.45/bin/startup.sh &  
         
        
